name: Python CI (Windows)

on: [push]

jobs:
  build:

    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
        #ubuntu-latest,
        windows-2016
        ]

    env:
      WORKON_HOME: cache/venv
      PIPENV_CACHE_DIR: cache/pipenv
      OSMNX_CACHE_DIR: cache/osmnx

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9.2"
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: cache
        key: ${{ runner.os }}-cache-${{ hashFiles('Pipfile.lock') }}

        restore-keys: ${{ runner.os }}-cache-
    - name: Install dependencies
      run: pip install pipenv && pipenv sync -d
    - name: Check formatting
      run: pipenv run format --check
    - name: Linting
      run: pipenv run lint
    - name: Run tests
      run: pipenv run test -vv --cov=registered --cov-fail-under=74
