name: Python

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      WORKON_HOME: cache/venv
      PIPENV_CACHE_DIR: cache/pipenv
      OSMNX_CACHE_DIR: cache/osmnx
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Set up Python
      run: uv python install
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: cache
        key: ${{ runner.os }}-cache-${{ hashFiles('uv.lock') }}
        restore-keys: ${{ runner.os }}-cache-
    - name: Install dependencies
      run: uv sync
    - name: Check formatting
      run: bin/format
    - name: Linting
      run: bin/lint
    - name: Run tests
      run: bin/test -v --cov=registered --cov-fail-under=74 --cov-report=term --cov-report=html
    - name: Check if coverage was reported
      id: has-coverage
      if: ${{ always() }}
      run: test -d htmlcov && echo "exists=true" >> $GITHUB_STATE
    - name: Upload coverage artifact
      if: ${{ always() && steps.has-coverage.outputs.exists }}
      uses: actions/upload-artifact@v4
      with:
        name: python-coverage-report
        path: htmlcov/
